[package]
name = "rdif-intc"
version = "0.12.1"
edition.workspace = true
authors = ["周睿 <zrufo747@outlook.com>"]
repository.workspace = true
license = "MIT"
description = "Driver Interface of interrupt controller."
keywords = ["os", "driver"]
categories = ["embedded", "no-std"]

[dependencies]
rdif-base = { workspace = true }
cfg-if = "1.0"
thiserror = { version = "2", default-features = false }
