[package]
authors = ["周睿 <zrufo747@outlook.com>"]
categories = ["embedded", "no-std"]
description = "Driver Interface net definition."
edition.workspace = true
keywords = ["os", "driver"]
license = "MIT"
name = "rdif-net"
repository.workspace = true
version = "0.1.0"

[dependencies]
rdif-base = { workspace = true }
