[package]
edition.workspace = true
name = "enumerate"
publish = false
version = "0.1.0"

[dependencies]
env_logger = "0.11"
log = "0.4"
rdrive = {path = "../../rdrive"}
rdif-intc = { version = "0.12", path = "../../interface/rdif-intc"}
