[package]
authors = ["周睿 <zrufo747@outlook.com>"]
categories = ["embedded", "no-std"]
description = "Driver Interface base definition."
edition.workspace = true
keywords = ["os", "driver"]
license = "MIT"
name = "rdif-base"
repository.workspace = true
version = "0.7.0"

[features]

[dependencies]
as-any = "0.3.2"
async-trait = "0.1"
rdif-def = "0.2.0"
thiserror = {version = "2", default-features = false}
paste = "1"

[dev-dependencies]
tokio = {version = "1", features = ["full"]}
