name: Check, Build and Test

on:
  push:
  pull_request:
    branches: 
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [stable]
        targets: [x86_64-unknown-linux-gnu]
        
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: clippy, rustfmt
        targets: ${{ matrix.targets }}
    - uses: Swatinem/rust-cache@v2
    - name: Install qemu
      run: sudo apt install qemu-system-aarch64 -y
    - run: sudo apt install u-boot-tools -y
    - name: Install lib libudev-dev
      run: sudo apt install libudev-dev -y
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --target ${{ matrix.targets }} --all-features
    - name: Build
      run: cargo build --target ${{ matrix.targets }} --all-features
    - name: Unit test
      if: ${{ matrix.targets == 'x86_64-unknown-linux-gnu' }}
      run: cargo test --target ${{ matrix.targets }} -- --nocapture
